name: Curso Django

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.10.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.7
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -q pipenv
          pipenv sync -d
      
      - name: Lint with flake8
        run: |
          pipenv run flake8 .

      - name: Tests with pytest
        run: |
          pipenv run pytest --cov=pypro

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
